### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by barakthecat** [dzungpv/mitsubishi2MQTT#31]
I'm able to get Gysmo38's original fork to build and upload, but I am getting the following error in ArduinoIDE. Any suggestions?

/Users/jason/Documents/Arduino/mitsubishi2MQTT-dzungpv/main/main.ino: In function 'void setup()':
/Users/jason/Documents/Arduino/mitsubishi2MQTT-dzungpv/main/main.ino:270:25: error: no matching function for call to 'HeatPump::connect(USBCDC*)'
       hp.connect(&Serial);
                         ^
In file included from /Users/jason/Documents/Arduino/mitsubishi2MQTT-dzungpv/main/config.h:57,
                 from /Users/jason/Documents/Arduino/mitsubishi2MQTT-dzungpv/main/main.ino:17:
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:244:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*)'
     bool connect(HardwareSerial *serial);
          ^~~~~~~
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:244:10: note:   no known conversion for argument 1 from 'USBCDC*' to 'HardwareSerial*'
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:245:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*, int)'
     bool connect(HardwareSerial *serial, int bitrate);
          ^~~~~~~
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:245:10: note:   candidate expects 2 arguments, 1 provided
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:246:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*, int, int)'
     bool connect(HardwareSerial *serial, int rx, int tx);
          ^~~~~~~
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:246:10: note:   candidate expects 3 arguments, 1 provided
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:247:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*, int, int, int)'
     bool connect(HardwareSerial *serial, int bitrate, int rx, int tx);
          ^~~~~~~
/Users/jason/Documents/Arduino/libraries/HeatPump/src/HeatPump.h:247:10: note:   candidate expects 4 arguments, 1 provided

exit status 1

Compilation error: no matching function for call to 'HeatPump::connect(USBCDC*)'

**Comment by dzungpv** [comment]
You can follow the guide: https://github.com/dzungpv/mitsubishi2MQTT?tab=readme-ov-file#how-to-build-code-from-source
I see you are using Arduino, try to install libs match version in the config, not the latest one and retry.
You can see libs here: https://github.com/dzungpv/mitsubishi2MQTT/blob/master/platformio.ini.
Note that I use the HeatPump lib fork in my account, not the original one, because the maintainer not merge my code. The best solution you install PlatformIO or download Github ci build here: https://github.com/dzungpv/mitsubishi2MQTT/actions/workflows/build.yml
